### ISSUE TITLE
【内容分享】ChatMart：为网站和文档定制 AI 聊天机器人

### ISSUE THREAD

**Issue by kerrygao** [Eternaldeath/AIProductHome#3]
/*请提供高质量的 AI 工具（模型，科普教程，友情仓库或网站），请不要提供包含政治敏感，色情和欺诈等性质的内容*/

**工具名称**：ChatMart

**工具简介**：为网站和文档定制 AI 聊天机器人，并可集成在任何网站。用例：文档总结、文档对话、知识共享、论文/报告研究、教学助手、企业培训、客户支持、网站搜索、导购推荐、销售支持...

**【可选】官方网站**：https://www.chatmart.co

**【可选】Github**：-

**【可选】其他链接**：-

**Comment by Eternaldeath** [comment]
感谢分享，预计在本周更新（2024.1.7）中添加该工具。

**Comment by Eternaldeath** [comment]
❤️ 分享已更新。

**Comment by kerrygao** [comment]
好的好的 非常感谢

noname ***@***.***> 于2024年1月7日周日 10:45写道：
