### ISSUE TITLE
【内容分享】好工具

### ISSUE THREAD

**Issue by 2258550147** [Eternaldeath/AIProductHome#4]
Note：您可以在这里分享高质量的 AI 工具，模型，科普教程或者友情链接。注意，不要提供包含政治敏感，色情和欺诈性质的内容。最后，感谢您的分享。

**工具名称**：好工具

**工具简介**：本站提供AI工具使用教程，如何写论文等等，还有chatgpt4账号购买、gpt4账号购买
、chatgpt plus账号购买、gpt4api账号、chatgpt plus共享合租账号购买、gpt plus 代充业务。

**【可选】官方网站**：https://haogonju.com/

**【可选】Github**：若存在 Github，在冒号之后提供 Github 链接。

**【可选】其他链接**：若存在其他必要链接，在冒号之后提供必要链接。

**Comment by Eternaldeath** [comment]
感谢分享，预计在本周更新（2024.1.28）中添加该工具。

**Comment by Eternaldeath** [comment]
❤️ 分享已更新。
