### ISSUE TITLE
【内容分享】SmallAI：集合140款AI大模型一键使用包含Claude3.5、GPT4o、GeminiPro、Midjourney等

### ISSUE THREAD

**Issue by Xiaokai6880** [Eternaldeath/AIProductHome#6]
**工具名称**：SmallAI

**工具简介**：支持一键使用GPT全系列、Claude全系列、微软必应全系列、谷歌Gemini全系列、国内全系列主流模型、向量模型（Embedding）、文生音频模型（Suno）、AI绘画模型（DallE3、Midjourney）、文生视频模型（luma-video）等超过140款AI模型

**官方网站**：www.smallai.asia

**一键获取Key**：Shop.SmallAI.Asia

**Comment by Eternaldeath** [comment]
感谢分享，内容检查后于下期更新中进行提交。

**Comment by Eternaldeath** [comment]
分享已更新。
