### ISSUE TITLE
有没有一个分类专门用来放PC客户端助手的？例如豆包出了客户端，还有其他家出客户端啥的

### ISSUE THREAD

**Issue by chenbihao** [Eternaldeath/AIProductHome#7]
例如抖音的豆包出了客户端，
还有其他家出客户端啥的

还有个人开发的  AI 0x0 之类的

**Comment by Eternaldeath** [comment]
感谢建议，目前已经在重构仓库的分类，采用小步快跑的方式逐渐更新分类，您提供的建议也会纳入优化的计划中。
